### ISSUE TITLE
Allow styling via CSS classes/CSS-Modules

### ISSUE THREAD

**Issue by davidkpiano** [Adphorus/react-date-range#1]
Is it possible to make the inner components able to be styled without having to resort to inline styles?

**Comment by burakcan** [comment]
https://github.com/Adphorus/react-date-range/pull/3

**Comment by burakcan** [comment]
https://github.com/Adphorus/react-date-range/releases/tag/v0.1.5

**Comment by davidkpiano** [comment]
Thank you! :+1:
