### ISSUE TITLE
DateRange: Changing date in one calendar resets the date in the other

### ISSUE THREAD

**Issue by tarun-dugar** [Adphorus/react-date-range#107]
I am using the `DateRange` component. If I select a `startDate` and `endDate` from the two calendars and then edit the date in one of the calendars, the date in the other calendar is also set to the date I selected in the first calendar.

Is there a way to maintain the date I selected in the other calendar irrespective of what I selected in the first calendar via `props` or a workaround maybe?

**Comment by cemarguvanli** [comment]
Can you show your component?

**Comment by tarun-dugar** [comment]
@cemarguvanli , here' how I am using it:

```
handleSelectDateRange(range) {
    this.setState({
      'startDate': range.startDate,
      'endDate': range.endDate
    });
 }

<DateRange
    onChange={this.handleSelectDateRange.bind(this)}
    maxDate={moment()}
 />
```

**Comment by burakcan** [comment]
@cemarguvanli could you find a solution for this?

**Comment by mkg0** [comment]
Hi @tarun-dugar, I'm sorry we couldn't consider your issue.
We deprecated this version. Could you please upgrade the new one.
