### ISSUE TITLE
Ability to color some specific dates or date ranges

### ISSUE THREAD

**Issue by wer** [Adphorus/react-date-range#11]

**Comment by burakcan** [comment]
Can you give some detail pls? Do you mean coloring holidays etc.?

**Comment by wer** [comment]
You have done very nice work, but a lot of critical things are missing:
1. minDate, maxDate
2. disable specific dates
3. coloring specific dates (in other words provide a class for specific dates, or date ranges)

**Comment by wer** [comment]
You can also provide a function onRenderDay and let the developer decide what to do
