### ISSUE TITLE
DateRange component changes months if I select whole date range in one Calendar

### ISSUE THREAD

**Issue by iJoyCode** [Adphorus/react-date-range#110]
Hello,

If you try to setup default DateRange component `<DateRange/>` and try to select whole date period on left calendar, you will see that component rapidly change months.
I can reproduce on master branch's demo, but can't on http://adphorus.github.io/react-date-range/
Seems like something is broken.

**Comment by ikhattab** [comment]
I had the same issue

**Comment by njnest** [comment]
It works correctly just in 0.2.4 version ((

**Comment by bl-brandon** [comment]
Seeing this issue as well.
