### ISSUE TITLE
DateRange: selecting the same day again provides different startDate

### ISSUE THREAD

**Issue by jayphelps** [Adphorus/react-date-range#114]
Using DateRange, if you click on the same day that is already selected it will give you a `startDate` that is different than the one previous. It alternates back and forth between `23:59:59` and `00:00:00` for that given day.

Demo: https://www.webpackbin.com/bins/-KejXyJ7CpDyWtH4MGZB

```js
const Example = () => (
  <DateRange
    onChange={({ startDate, endDate }) => {
      console.log(startDate.format());
      // 2017-03-08T23:59:59-08:00
      // 2017-03-08T00:00:00-08:00
      // 2017-03-08T23:59:59-08:00
      // etc...
    }}
  />
);
```

For many locales, this will cause the local day to flip back and forth between the correct day and the day before it.

Taking a look at the source, one thing I noticed is that `startOf` is used sometimes as if it creates a new moment, when it fact it mutates the applied moment in-place. This may be unrelated, obviously.

**Comment by mkg0** [comment]
I'm closing this issue due to dropped old version support.
