### ISSUE TITLE
Provide an option to use classes instead of hardcoded styles

### ISSUE THREAD

**Issue by wer** [Adphorus/react-date-range#12]

**Comment by burakcan** [comment]
Do you mean the ability to completely disabling of the default styles?

**Comment by wer** [comment]
i want to be able, to assign custom classes like
i) selected
ii) selected-start
iii) selected-end
iv) selected-range

**Comment by burakcan** [comment]
I see. Css classnames are already available (.rdr-DateRange, rdr-Calender etc.). But there are no way to disable default styling for now. Having an option like `onlyClasses: true` can be nice for extended custom styling support. Thanks.
