### ISSUE TITLE
How to make it disappear? The Date Range picker is always show

### ISSUE THREAD

**Issue by wzup** [Adphorus/react-date-range#127]
Date pickers normally appear after a user clicks some field, like this, for example

![1124x977 - google chrome 2017-04-10 18 23 38](https://cloud.githubusercontent.com/assets/3880497/24857952/bd392cdc-1e1c-11e7-8e3b-4d93465dc3ea.png)

But your date picker is always shown. Is there a way to make it appear on click events?

![form - google chrome 2017-04-10 18 39 13](https://cloud.githubusercontent.com/assets/3880497/24858040/11f3ad56-1e1d-11e7-8234-ddd489112823.png)

**Comment by burakcan** [comment]
react-date-range doesn't provide a way for hiding/showing. You should implement it in your app by conditionally rendering.
