### ISSUE TITLE
When using as a controlled element, the component tempers with parent data

### ISSUE THREAD

**Issue by samueldelesque** [Adphorus/react-date-range#129]
If I do something like:
```
<DateRange
    onChange={ value => this.handleDateSelect(value) }
    startDate={ this.state.startDate }
    endDate={ this.state.endDate }
/>
```
Where my parent component modifies this.state.startDate and this.state.endDate (in my case, I was adding the option to specify a time, or enter a date manually via input field), React-Date-Range tempers with the memory value of those fields which makes it really confusing (it took me a few hours of debugging to find out what was happening).

~The solution to this issue is to use a clone of the startDate/endDate instead of changing those elements themselves. I can pass `this.state.startDate.clone()` and it will work, but this should be implemented inside the component - on componentWillReceiveProps.~ Just saw that this is already being done... Not sure why it's not working properly then.

**Comment by mkg0** [comment]
should be resolved in the new version
