### ISSUE TITLE
u need add package ---- "prop-types"

### ISSUE THREAD

**Issue by ZweiZhao** [Adphorus/react-date-range#130]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

new react need "prop-types", else console that.

**Comment by hqro** [comment]
more informations: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by kazazor** [comment]
I submitted a PR to address this issue.

If someone can quickly review it, merge and publish that would be great :)

**Comment by coockoo** [comment]
Hey! I've noticed a fix was merged and version bumped already.
Can you publish it to npm?
Thank you in advance.
