### ISSUE TITLE
DayCell Parent spans classes.

### ISSUE THREAD

**Issue by skmail** [Adphorus/react-date-range#131]
Hello,

First of all, Many thanks for this cool component.

It would be better to add DayCell classes (is-selected, is-inRange)  on the parent  span instead of the inner span to get better control when styling the cells. 

so some styling like the following can be applied:
```
.is-inRange:first-child{};
.is-selected:not(:nth-child(7n + 1)){}
/* and many */ 
```

I'm not sure if i can do something similar to the code above, If yes please let me how, if not, i've no problem to make PR  for this but let  me know your thoughts first.

What do you think?

Best Regards.

**Comment by skmail** [comment]
Ok,  after digging into the code i figured out that  i can use the following:

```
<DateRange
    classNames={{
        dayStartEdge:"day-range-start",
        dayEndEdge:"day-range-end"
    }}/>
```

Thank you.

**Comment by hipdev** [comment]
Hey, this is not working anymore, there is a way to add a className to the parent day button tag ? I need to add a class to the parent to style in a different way
