### ISSUE TITLE
No info about breaking changes (Releases or CHANGELOG.md)

### ISSUE THREAD

**Issue by davidmason** [Adphorus/react-date-range#145]
I am trying to update from 0.2.4 to the latest release, but I have no straightforward way to tell if there have been any breaking changes.

Please provide a list of additions, bugfixes and breaking changes as part of the release process. `CHANGELOG.md` or https://github.com/Adphorus/react-date-range/releases would be the first places I would look for such information.

Related (but not a long-term fix): can anyone tell me whether there are any breaking changes between `0.2.4` and `0.9.4`?

**Comment by mkg0** [comment]
thanks for spot @davidmason 
We know the critic problems. We will depreciate current version after several minor/patch releases to making stable.
The new version will cover this kind of problems(changelog, contribution guide, regard to semver and test running)

I close this issue. You can find details at readme soon. Thank you for your care.
