### ISSUE TITLE
Locales issue:

### ISSUE THREAD

**Issue by meyve** [Adphorus/react-date-range#148]
Hey there! 
First of all, thanks for your awesome datepicker. 
Here is list of some problems I met using your component:

- Russian locales not working at all.
- French, Italian, German,  months' names are displayed as whole word instead of first two characters.

**Comment by meyve** [comment]
![selection_011](https://user-images.githubusercontent.com/19283375/27793382-7c6043c2-6006-11e7-8f96-ab976e04bcdb.png)

**Comment by meyve** [comment]
I've read most of the issues of this repository and, I assumes, authors does not support it anymore. So I decided to fork your project and fix minor locale bugs on my own.

You can find updated package here:
https://www.npmjs.com/package/react-date-range-updated

All credits goes to Adphorus as mentioned in README.
Cheers :d

**Comment by Yessengerey** [comment]
@meyve Thank you very much for your update! The Russian translation works like a charm!
