### ISSUE TITLE
Question - no selection possibility

### ISSUE THREAD

**Issue by juklicek** [Adphorus/react-date-range#151]
Hy there,

sorry if I overlook something, but I am missing simple thing: is there a possibility to set daterange picker to "nothing selected" state? In my app "no filter" is default satate, so I would like to set picker to this state too... When I put null to startDate/endDate it sets to default (today).

Thanks for help!

**Comment by noelianunez** [comment]
@juklicek where you able to figure out how to do it? I'm trying to do the same

**Comment by Sinequanonh** [comment]
Also looking for a solution 🙏 Couldn't come up with anything yet

**Comment by noelianunez** [comment]
@Sinequanonh I was able to clear the dates like this:
<Button className="search--reset-date" color="link" type="button" onClick={() => this.setState({ dateRange: {startDate: 0, endDate: 0}}) }>Clear dates</Button>

**Comment by onurkerimov** [comment]
I'm closing this, since it has been answered.
