### ISSUE TITLE
Changing date outside of component doesn't affect the component

### ISSUE THREAD

**Issue by tehbi4** [Adphorus/react-date-range#158]
Hello, I have a scenario where date is a React state property, that can be changed anywhere in the app. However when it happens the date on component stays the same (it wont update).

Here is the minimalistic scenario for bug reproducing. A button click increases the date by one day.
```javascript
import React from 'react';
import { Calendar } from 'react-date-range';
import moment from 'moment';

class BugExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      date: moment(),
    }
  }

  render() {
    return (
      <div>
        <button onClick={() => this.setState({ date: this.state.date.add(1, 'day')})}>
          Next date
        </button>
        <Calendar date={this.state.date} />
      </div>
    );
  }
}

export default BugExample;
```

There is [codesandbox.io demo](https://codesandbox.io/embed/yj4xwlzprx)
The same problem was in #112

react-date-range version: 0.9.4

**Comment by mkg0** [comment]
fixed in the new version
