### ISSUE TITLE
"lang" prop not working 

### ISSUE THREAD

**Issue by esti-magnet** [Adphorus/react-date-range#159]
Hey, 
I'm having trouble trying to change the language: "lang" prop doesn't seem to work (latest release). 
Am I doing it wrong? Is there any way to change the language without hard coding it?
There is my clojure code just for you to see the way that I'm trying to change language. The rest of the functionality (firtsDayOfWeek and onChange ) is working fine.

          (js/React.createElement    js/ReactDateRange.DateRange
          (let [lang (re-frame/subscribe [:selected-language])]
          #js {:lang "es"
               :firstDayOfWeek (cond
                                 (= (str @lang) ":es") 1
                                 (= (str @lang) ":en") 7)
               :onChange #(reset! temp-range [(-> % js->clj (get "startDate") .valueOf)
                                              (-> % js->clj (get "endDate") .valueOf)])}))`

**Comment by mkg0** [comment]
fixed in the new version
