### ISSUE TITLE
help: Datepicker range reset feature

### ISSUE THREAD

**Issue by rob1121** [Adphorus/react-date-range#162]
Can someone help me how to reset the datepicker to its default #

**Comment by noelianunez** [comment]
Just in case any one else has same issue as me:

I was able to fix it updating the state to null

`this.setState({ dateRange: {startDate: null, endDate: null}})`

**Comment by mkg0** [comment]
Hi @rob1121, I hope @noelianunez's answer helped you. I can advice you to upgrade next version because it's easier to control data declarative way.
I will close this issue due to inactivity. If you have any question about the new version you can open a new issue as well.

**Comment by ajay7868** [comment]
Hi 
**i am still facing Datepicker range reset feature ,date is not reset when i used same way .please help out 
where we define state like this** 
dateRange: {
            selection: {
                startDate:null,
                endDate:null,
                key: 'selection',
                color: '#5dc97c',
            },
now i make button for reset these value using 

this.setState({ dateRange: {startDate: null, endDate: null}})
