### ISSUE TITLE
Datepicker repeated days

### ISSUE THREAD

**Issue by dehmirandac2** [Adphorus/react-date-range#163]
My DateRange component is showing repeated days (October, 16). I think that this is happening because of timezone in Brazil. 
But when I load the Calendar component from react-date-range, it works fine.
Could you please help me to understand what is happening with DateRange component? 
Or how can I fix it?
Thanks!
![date-range-error](https://user-images.githubusercontent.com/8313529/32022039-ff6ad37a-b9b3-11e7-84c8-1a4ea3c6cc60.png)

**Comment by mkg0** [comment]
fixed in the new version
