### ISSUE TITLE
react-date-range needs only react version 14/15 and not 16

### ISSUE THREAD

**Issue by Senthilthirunavukkarasu** [Adphorus/react-date-range#166]
Hi, i have react 16.1.1 installed and when i tried to install react-date-range@0.9.4 which is the latest version, still it reports a warning "npm WARN react-date-range@0.9.4 requires a peer of react@^0.14 || ^15.0.0-rc || ^15.0 but none was installed." Can someone help?

**Comment by hampusohlsson** [comment]
+1 it works fine with React 16, just need to update package.json

**Comment by reduxdj** [comment]
+1. mind updating your dependency please?

**Comment by epifab** [comment]
it actually doesn't seem to work with react 16 for me...

**Comment by epifab** [comment]
this is the message if I try to use it out of the box: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by epifab** [comment]
I actually found out what the problem was. apparently, even if I'm only using the `DateRange` component I have to import the` Calendar` one. this seems to have fixed it

**Comment by kibertoad** [comment]
Any chance you could release the version with updated package.json?..

**Comment by nescalante** [comment]
+1, it seems that the fix is tagged but its not released to NPM

https://github.com/Adphorus/react-date-range/releases/tag/v0.9.5-0

**Comment by medington** [comment]
I'm in the process of upgrading a project from React 15 to 16 and it's really unclear to me what the status is for this package for use with React 16. @nescalante noted above there is a tag for a `0.9.5` release but no release on npm. Could someone perhaps elaborate on the status of that?

Beyond that I think something in the readme is warranted here. I'm lost on what I should do at this point to get beyond basic errors from npm. Thanks in advance for any pointers.

**Comment by medington** [comment]
I finally settled on installing the HEAD of the `v0` branch from GitHub rather than relying on the published version of 0.9.4 on npmjs.com. I opted to use the tag using the following command:

```npm install Adphorus/react-date-range.git#36f481daad567ec4267a4afd95460bd14a6231ac```

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0) Thank you for pointing it out. I'm closing this.
