### ISSUE TITLE
How to clear selection? 

### ISSUE THREAD

**Issue by jpomykala** [Adphorus/react-date-range#169]
I tried pass `undefined` and `null` values to `endDate` & `startDate` but `DateRange` component ignores this

**Comment by jimjamO** [comment]
I also wish to have nothing selected initially. Can this be done?

**Comment by noelianunez** [comment]
I'm trying to do the same, did you find any solution? I haven't figured it out.

I tried:

`this.dateRanges = {
      'Anytime'         : {
        startDate     : () => {
          return null;
        },
        endDate       : () => {
          return null;
        }
      }
}`

But does not work

**Comment by noelianunez** [comment]
I was able to do it! 

'this.setState({ dateRange: {startDate: null, endDate: null}}'

**Comment by jimjamO** [comment]
@noelianunez Where did you put this code? Will it clear the selection, as shown here:
![image](https://user-images.githubusercontent.com/1471350/35732485-6b55263e-0811-11e8-9431-e6a14b863d85.png)

**Comment by jpomykala** [comment]
In my case worked setting current date like this
`this.setState({ startDate: moment(), endDate: moment() });`

**Comment by jimjamO** [comment]
@jpomykala This does not work for me, I regardless of what I passed as startDate/endDate. I've tried null, empty string, and now moment(). All result in the current date being set to Today (as in my above screenshot).

Where did you set these values? For clarity, here is my usage:

`import React from 'react';
import { DateRange } from 'react-date-range';
 
export default class extends React.Component{
    render(){
        console.log("Date Range: ", this.props.startDate, this.props.endDate);
        return (            
            <DateRange 
                onInit={this.props.handleSelect}
                onChange={this.props.handleSelect}
                firstDayOfWeek={1}
                startDate={this.props.startDate}
                endDate={this.props.endDate}
                format={"YYYY/MM/DD"}
                twoStepChange={true}
                calendars={1}
            />
        );
    }
}`

**Comment by jpomykala** [comment]
I got the same problem, I don't know why it starts working. 😅

**Comment by noelianunez** [comment]
@jimjamO I Have a dropdown that displays the values of the daterange selected

```<DropdownToggle caret outline
                onClick={this.toggle}
                data-toggle="dropdown"
                aria-expanded={this.state.dateDropdownOpen}>
                <i className="fa fa-calendar"></i>
                { !this.state.dateRange['startDate'] && !this.state.dateRange['endDate'] ? ' Anytime' : ''}
                { this.state.dateRange['startDate'] ? this.state.dateRange['startDate'].format(format).toString() : '' }
                { this.state.dateRange['endDate'] ? ' - ' + this.state.dateRange['endDate'].format(format).toString() : ''}
              </DropdownToggle>````

And with this reset button, the text goes back to Anytime and the startDate and endDate are passed in the submit of the form as 0.

Hope it helps you :)

**Comment by jimjamO** [comment]
@noelianunez But what do you pass to the <DateRange> itself? Are you saying pass in the dateRange with startDate and endDate being null? (as below) I have tried and it does not work.

```
<DateRange 
                onInit={this.props.handleSelect}
                onChange={this.props.handleSelect}
                firstDayOfWeek={1}
                dateRange={{startDate: this.props.startDate, endDate: this.props.endDate}}
                format={"YYYY/MM/DD"}
                twoStepChange={false}
                calendars={this.props.calendarStyle}
            />
```
