### ISSUE TITLE
Customize number of day cells in a month else default it to 42 cells(6*7)

### ISSUE THREAD

**Issue by kosiganti** [Adphorus/react-date-range#171]
https://github.com/Adphorus/react-date-range/blob/4bab53471f58d9b68838bad54610e0018d7c2b5b/src/Calendar.js#L208

**Comment by kosiganti** [comment]
It would be helpful to be able to customize the number of days that appear in a month instead of showing 42 cells for every month

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0)
Now you can set `fixedHeight` prop to `true` if you want all the months to appear in 6 rows.
Thank you for pointing it out. I'm closing this.
