### ISSUE TITLE
Italian weekdays uses extended names

### ISSUE THREAD

**Issue by MatteoMilesi** [Adphorus/react-date-range#175]
Italian translation of weekdays uses the extended names instead of the two-letters version, causing spacing problems.

<img width="564" alt="schermata 2018-01-20 alle 16 14 24" src="https://user-images.githubusercontent.com/6038939/35185020-a4b3b472-fdfd-11e7-9f3e-1621d673f160.png">

Accordingly to the other localizations, the correct names should be:

```
'su':'Do',
'mo':'Lu',
'tu':'Ma',
'we':'Me',
'th':'Gi',
'fr':'Ve',
'sa':'Sa'
```

Also the first letter of the months names should be uppercase.

**Comment by mkg0** [comment]
Hi @MatteoMilesi, we dropped support v0s and preparing to release the new version. It's supporting Italian lang too. Could you please upgrade the new version.
