### ISSUE TITLE
How hide/show the date ranger picker component

### ISSUE THREAD

**Issue by harkinj** [Adphorus/react-date-range#177]
Hi,
Thanks for the great control.
We initially want the control displayed but when the user has picked a start and end date to have it "hide" with the ability to show again as needed by the users. Can the control be configured to support this or do we need to implement the show/hide ourselves via a button or the like?
Thanks for all info.
John

**Comment by dcworldwide** [comment]
I wrapped the control in a material ui popover. The current design is more modular.

**Comment by mkg0** [comment]
We don't want to provide show/hide feature, this is not in this library's context.

**Comment by phutngo** [comment]
> We don't want to provide show/hide feature, this is not in this library's context.

Could you provide some guidance or documentation on how to do this?
