### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by kaioduarte** [Adphorus/react-date-range#181]
pt-br and a couple langs are unavailable for me on v0.9.4.

![image](https://user-images.githubusercontent.com/11046907/37660567-783ffe2a-2c31-11e8-8fa7-0c4bad7349ef.png)

**Comment by mkg0** [comment]
Hey @kaioduarte, at the new version localization dependent on `date-fns`'s locales and we dropped support for this version. The new version could be a solution for you. If not you can open an issue at `date-fns` repo for locale support request.
