### ISSUE TITLE
React 16/npm warning 

### ISSUE THREAD

**Issue by andrewhathaway** [Adphorus/react-date-range#184]
Hey! Any chance we can get a quick 0.9.5 update that fixes the following issue please? When upgrading to React 16.X, on 0.9.4 you get the following npm warning:

```
npm WARN react-date-range@0.9.4 requires a peer of react@^0.14 || ^15.0.0-rc || ^15.0 but none is installed. You must install peer dependencies yourself.
```

Thanks!

**Comment by keremciu** [comment]
Hello @andrewhathaway 

There's a new version of the component, can you try that one?
https://github.com/Adphorus/react-date-range/tree/next

You can install it like `npm install react-date-range@next`

**Comment by andrewhathaway** [comment]
Hi @keremciu! I did see there as an alpha update on the releases page, however it's an alpha and I also saw breaking changes, so didn't want to roll with that just yet!

**Comment by andrewhathaway** [comment]
@mkg0 So this is a no? No explanation why my issue is closed.

**Comment by mkg0** [comment]
@andrewhathaway sorry for no explanation Andrew.
We deprecated 0.x version support and don't have any plan to new releases on it. Could you please upgrade package for preventing the warning?

**Comment by andrewhathaway** [comment]
I would love to, however there is no release out of a beta/alpha release that I can use? I'm not wanting to migrate to an alpha version, that is likely to change or may potentially have bugs.

**Comment by andrewhathaway** [comment]
Without sounding like an arsehole, #198 is good example of why I can't use alpha versions in a product! :(
