### ISSUE TITLE
(calendar header) Add ability to show month and year instead of month and year selectors

### ISSUE THREAD

**Issue by ydagana** [Adphorus/react-date-range#205]
## Subject of the issue
Feature: my employer wanted to remove the month and year selectors from the calendar header and instead just display the month and year.

It would be nice to have a prop like showMonthAndYearPickers, default to 'true' that we can simply set to false if we don't want to display the month and year selectors.

**Comment by mkg0** [comment]
Will be released next alpha version

**Comment by ydagana** [comment]
@mkg0 Do you have an estimation when the next alpha version will be released? 
Thanks

**Comment by ydagana** [comment]
@mkg0 Thanks much!

**Comment by tlr3552** [comment]
This bummed me out to find, because now we always have something displayed and we have no way to remove it via props.
