### ISSUE TITLE
'Proxy' is undefined in IE browser

### ISSUE THREAD

**Issue by rajeshmalisetty** [Adphorus/react-date-range#208]
## Subject of the issue
 I am getting the **'Proxy' is undefined** issue when I am trying to open in IE browser
 
## [BUG] Bug Reproduce Steps
check by open demo URL  [http://adphorus.github.io/react-date-range](http://adphorus.github.io/react-date-range) in IE

**Issue can be screen in console log** 

## Environment
Package Version: "^1.0.0-alpha5"
React version:  "^16.3.1"
Browser: IE

The issue in IE screenshot for my project

![datepicker issue](https://user-images.githubusercontent.com/8476243/40602944-0401ada6-6278-11e8-8303-d695b1bfb949.PNG)

**Comment by mkg0** [comment]
fix on `master` branch. It will be released with next `alpha` release.

thank you for report it 🙂

**Comment by artusi** [comment]
Hey @mkg0 awesome library! Nice to see this fix!!

Do you guys have any ideia when you will be pushing the next release?
