### ISSUE TITLE
Month and Year pickers and Month arrows don't work

### ISSUE THREAD

**Issue by kiskacsa08** [Adphorus/react-date-range#209]
## Subject of the issue
We use the latest version of your module. We have an issue with the month and year pickers and month arrows. They are rendered, but nothing happens when clicking on them. We maintain properly ranges and we can see the selected ranges highlighted but we cannot select month/year. Nor the select components neither the buttons work.
 
## [BUG] Bug Reproduce Steps
Click on the month arrow button or select year/month from the dropdowns.

## [BUG] Expected behaviour
Change the month and change the year accordingly to the button function

## Environment
Package Version: react-date-range@0.9.4
React version: react@16.4.0
Node version: node@10.3.0
Browser: Google Chrome 66.0.3359.117 (64 bit)  and Firefox Quantum 59.0.2 (64 bit)

**Comment by bmr1** [comment]
i also get this issue

**Comment by wethil** [comment]
We do not have separated month/year picker in the v0.9.x, we have at the last version.
