### ISSUE TITLE
Block some dates inside Range

### ISSUE THREAD

**Issue by chandraflyrobe** [Adphorus/react-date-range#213]
## Block some dates inside Range
If I want to block some dates inside min and max range , How is it possible?
 
Like , minDate is  - 01/01/2018 and maxDate is 12/12/2018. Users can select some dates as input like  ,['03/03/2018', '27/03/2018', '05/06/2018', ....].

**Comment by mkg0** [comment]
Hi @chandraflyrobe 
It hasn't supported yet but it makes sense.
I will integrate it asap. Also PR's welcome.
