### ISSUE TITLE
Defined change locale

### ISSUE THREAD

**Issue by Reakzy** [Adphorus/react-date-range#214]
Hello,
Is it possible to change locale langage for DefinedRange?
i tried : 
import {fr} from "react-date-range/src/locale/index";

				`<DefinedRange
					ranges={[selectionRange]}
					onChange={this.handleChange}
					locale={fr}
				/>`
but it change nothing. Am i doing something wrong?

Thanks in advance

**Comment by mkg0** [comment]
Currently `react-date-range` doesn't provide localization support for default defined ranges. You can set your `staticRanges` and `inputRanges` with the locale texts.

Here is the default ranges: https://github.com/Adphorus/react-date-range/blob/master/src/defaultRanges.js

**Comment by Reakzy** [comment]
Is it the same for the format, in france one week start on Monday and end Sunday, but currently on the definedRange, it's Saturday to Sunday.
Do i have to change it directly in defaultRanges.js too?

**Comment by mkg0** [comment]
DefinedRange directly set dates itself. So it should care for local dates.

If you use `date-fns` for date operations you should set locale to options param. For example, if you set the start of week:

```js
import {startOfWeek} from 'date-fns';
import fr from 'date-fns/locale/fr';
const dateOptions = { locale: fr };

const startOfWeek = startOfWeek(new Date(), dateOptions);
// it will be monday
```
