### ISSUE TITLE
Range not definable by two clicks, only by dragging

### ISSUE THREAD

**Issue by GeovationMax** [Adphorus/react-date-range#216]
## Subject of the issue
Range not definable by two clicks, only by dragging
 
## [BUG] Bug Reproduce Steps

- Grab the latest react-date-range 1.0.0-beta
- Set up a DateRangePicker, for example like this:

```
<DateRangePicker
  showSelectionPreview={true}
  ranges={[this.state.rangeselection]}
  onChange={this.handleSelect}
  moveRangeOnFirstSelection={false}
  months={2}
  direction="horizontal"
/>
```
Initializing state like this:
```
this.state = ({
    rangeselection: {
        startDate: new Date(),
        endDate: new Date(),
        key: 'rangeselection'
    }
})
```
Handling the change like this:
```
handleSelect(ranges) {
    console.log(ranges)

    this.setState({
        ...ranges
    })
}
```

## [BUG] Expected behaviour

- The first click should select the start date of the range
- The second click should select the end date of the range

Instead I see this behavior:
- First click selects a date (start and end date the same in ranges onChange callback)
- Second click selects a new data (start and end date will be this same date)

## Environment
Package Version: 
React version: 16.4.0
Node version: 8.9.0
Browser: Firefox 60.0.2 / Chrome 67.0.3396.87

**Comment by bchhabra2490** [comment]
Use async/await to update the state in handleSelect().
`async handleSelect(ranges) {
   console.log(ranges);
    await this.setState({
        ...ranges
    })
}`

Maybe it will solve the problem.

**Comment by mkg0** [comment]
@GeovationMax  I haven't faced any problem with your example. Could you create a test repo for it?

**Comment by naren1213** [comment]
@mkg0 
I'm facing the same issue.
I want my onChange function to be called only after the range is set, so that i can make api call with both start and end dates. With this current behavior each time i click on start date, its calling my onChange function.

 Here is the screencast i made from your demo app. You need to enable flash player inorder to play this clip. https://www.screencast.com/t/PCqa0EHKS8S

**Comment by bchhabra2490** [comment]
```
changeStartDate(startDate) {
    this.setState({
      startDate,
    });
  }

  changeEndDate(endDate) {
    this.setState({
      endDate,
    });
  }

  handleDateChange(ranges) {
    this.changeStartDate(moment(ranges.selection.startDate).format('YYYY-MM-DD'));
    this.changeEndDate(moment(ranges.selection.endDate).format('YYYY-MM-DD'));
  }

```

I have passed `handleDateChange` function to Calendar Component and it is working fine. Ignore moment formatting. @naren1213

**Comment by bchhabra2490** [comment]
@naren1213 Well you can check if the endDate is greater than startDate in your onChange function and then make the api call.

**Comment by so1337** [comment]
Still present.
Range works well until you pass onRangeFocusChange prop - after which range selects only by dragging

**Comment by evorgevol** [comment]
I was having a similar issue, but realised it was because React was re-rendering my component as I was updating the value of the redux state property which was forcing it to render again, resulting in the described behaviour.

**Comment by eretica** [comment]
The reality of the code of DateRangePicker
https://github.com/hypeserver/react-date-range/blob/master/src/components/DateRangePicker/index.js#L34

need to self management focusedRange & onRangeFocusChange

```ts
const [focusedRange, setFocusedRange] = React.useState<[number, number] | undefined>(undefined);
<DateRangePicker
	showMonthAndYearPickers={false}
	onRangeFocusChange={(focus) => {
		setFocusedRange(focus)
	}}
/>

```
