### ISSUE TITLE
How to remove rdrDefinedRangesWrapper

### ISSUE THREAD

**Issue by dlodeprojuicer** [Adphorus/react-date-range#217]
## rdrDefinedRangesWrapper
Is there a way to hide/remove defined rage wrapper if there are no staticRanges and input Ranges?
This is what it looks like currently 
<img width="611" alt="screen shot 2018-07-11 at 12 39 34" src="https://user-images.githubusercontent.com/2291356/42566660-8c1552a4-8507-11e8-90d3-b814f6df81f0.png">
 
## [BUG] Bug Reproduce Steps

          <DateRangePicker
            ranges={[selectionRange]}
            onChange={this.rangeSelect}
            showMonthAndYearPickers={false}
            showDateDisplay={false}
            showSelectionPreview={false}
            showMonthArrow={false}
            staticRanges={[]}
            inputRanges={[]}
          />
## [BUG] Expected behaviour

I am trying to get this layout from [example 4 of demo link](http://adphorus.github.io/react-date-range/)
<img width="669" alt="screen shot 2018-07-11 at 12 38 46" src="https://user-images.githubusercontent.com/2291356/42566681-a42c694a-8507-11e8-95e0-54dde135c363.png">

## Environment
Package Version: "react-date-range": "^1.0.0-beta",
React version: "react": "^16.2.0",
Node version: v8.9.0
Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by mkg0** [comment]
`DateRangePicker` wraps `DefinedRange` component. If you don't need it you can use `DateRange` or `Calendar` components.

**Comment by mkg0** [comment]
Feel free to open this issue or ask any question.

**Comment by dlodeprojuicer** [comment]
This is by far the fastest response I have received from repo admin. Thanks.
