### ISSUE TITLE
Cannot read property 'clone' of null

### ISSUE THREAD

**Issue by pivcec** [Adphorus/react-date-range#218]
## Subject of the issue
When I try to open the following component, then I receive this error:

```
// props.issueDate = new Date();

import { Calendar } from 'react-date-range';

const IssueDatePopoverContent = (props) => {
  const { issueDate, handleIssueDateClick } = props;
  return <Calendar date={issueDate} onChange={handleIssueDateClick} />;
};
```

## [BUG] Expected behaviour
I would expect that the calendar should open as normal.

## Environment
Package Version:  "0.9.4",
React version: "16.3.0",
Node version: v8.11.2
Browser: Chrome 67.0.3396.87 (Official Build) (64-bit)

**Comment by mkg0** [comment]
Hi @pivcec 

you should use `next` tag if you want to use the beta version. `master` branch represent it.
Otherwise, you can check [this branch](https://github.com/Adphorus/react-date-range/tree/v0) if you want to use deprecated version.
