### ISSUE TITLE
Warning Using unescaped '#' characters in a data URI body is deprecated

### ISSUE THREAD

**Issue by destpat** [Adphorus/react-date-range#219]
## Subject of the issue

When i use your DateRangePicker component i have a warning

[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

## Environment
Package Version:  1.0.0-beta
React version: 16.4.1
Node version: 8.11.3
Browser: Chrome

**Comment by mkg0** [comment]
Hey @destpat

Thanks for reporting this! I pushed a commit to fix this. I will be released with the next version.

**Comment by alvintheodora** [comment]
Hi @mkg0 , When will the next version (after v1.0.0-beta) be released?
Thanks
