### ISSUE TITLE
library missing in package.json

### ISSUE THREAD

**Issue by in-ten-to** [Adphorus/react-date-range#226]
Hello,

In the package.json, "postcss" is missing.
When i try to build it manualy "yarn && yarn build"
i got an error : 
"/bin/sh: 1: postcss: not found
/bin/sh: 1: postcss: not found"

Is it possible to add it in the package please?

**Comment by mkg0** [comment]
It's fixed now
https://github.com/Adphorus/react-date-range/commit/fb0e92f273873948e14925c1be3b93c33a075290

Thanks for reporting.
