### ISSUE TITLE
Error when minDate and maxDate is null or undefined

### ISSUE THREAD

**Issue by Junbong** [Adphorus/react-date-range#227]
## Subject of the issue
Error occurred when `minDate` and `maxDate` of `<Calendar />` is `null` or `undefined`.
I tested this issue in demo page.
 
## [BUG] Bug Reproduce Steps
```jsx
<Calendar
  locale={rdrLocales[this.state.locale]}
  date={this.state.datePickerInternational}
  minDate={null}
  maxDate={null}
  onChange={this.handleChange.bind(this, 'datePickerInternational')}
  className={'PreviewArea'}
/>
```
![2018-08-02 8 11 23](https://user-images.githubusercontent.com/6138662/43580404-58e7d79a-9690-11e8-854c-bfbd9dd51185.png)
![2018-08-02 8 11 41](https://user-images.githubusercontent.com/6138662/43580415-60974106-9690-11e8-8add-4e7e974e61e6.png)

```jsx
<Calendar
  locale={rdrLocales[this.state.locale]}
  date={this.state.datePickerInternational}
  minDate={undefined}
  maxDate={undefined}
  onChange={this.handleChange.bind(this, 'datePickerInternational')}
  className={'PreviewArea'}
/>
```
![2018-08-02 8 13 35](https://user-images.githubusercontent.com/6138662/43580480-95f2de46-9690-11e8-9091-41a4b27637b3.png)

## [BUG] Expected behaviour
Work well with `minDate` and `maxDate`.

## Environment
Package Version: 1.0.0-alpha3
React version: react@16.4.2
Node version: v9.5.0
Browser: 67.0.3396.99

**Comment by mkg0** [comment]
Hi @Junbong 
It's not a bug. For both of `Calendar` and `DateRange`, max/min Dates should be defined. If you want to extend it to maybe next 2k years, still you can.

**Comment by Junbong** [comment]
@mkg0 Thanks for reply.
And then, how do I dynamically set the minimum date and the maximum date?
For example, if there are two calendars, depending on the status of each calendars, how `minDate` and `maxDate` could be changed? and how this values could be _CLEARED_?

**Comment by mkg0** [comment]
I don't know your use case but you can use min/max date props declaratively.

https://codesandbox.io/s/1o6z36404q

For an example calendars are bound and the second calendar's `minDate` is two days after the first calendar date.
