### ISSUE TITLE
DisabledDates does not work

### ISSUE THREAD

**Issue by atomoc** [Adphorus/react-date-range#231]
I saw that this was done a month ago, but for some reason this is not in the release, and I can not run the project from the master of the branch in any way.

Please help us to sort it out quickly!

**Comment by atomoc** [comment]
Or at least tell me when will the new release?

**Comment by atomoc** [comment]
Please replace:
`mv dist {YOUR_PROJECT}/node_modules/react-date-range`
to:
`mv dist {YOUR_PROJECT}/node_modules/react-date-range/`

Thanks!!!

**Comment by fabiovalencio** [comment]
just add the last version:
yarn add react-date-range@v1.0.0-beta2
