### ISSUE TITLE
Locale doesn't work

### ISSUE THREAD

**Issue by AlexeyCherneny** [Adphorus/react-date-range#234]
Demo
https://codesandbox.io/embed/88lxo421p2

Locale doesn't work.

```
import React from "react";
import ReactDOM from "react-dom";
import { DateRange } from "react-date-range";
import ru from "date-fns/esm/locale";

import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";

import "./styles.css";

function App() {
  return (
    <div className="App">
      <DateRange locale={ru} />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

package.json
```
{
  "name": "new",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "main": "src/index.js",
  "dependencies": {
    "date-fns": "2.0.0-alpha.16",
    "react": "16.4.2",
    "react-date-range": "1.0.0-beta",
    "react-dom": "16.4.2",
    "react-scripts": "1.1.4"
  },
  "devDependencies": {},
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by enderortak** [comment]
It is used in demo app like that:

`import * as rdrLocales from 'react-date-range/dist/locale';`
`<DateRange locale={rdrLocales.ru} />`

**Comment by enderortak** [comment]
Still localization does not change quick select buttons' text (today, yesterday etc.)

**Comment by snrmwg** [comment]
As far as I can see localization only affects date handling. The quick select buttons come from the DefinedRanges component and it is by default configured from the [defaultRanges.js](https://github.com/Adphorus/react-date-range/blob/2ffa7c861115e4d9cb9b50c8c9f14d274f143bd5/src/defaultRanges.js#L44).

As a workaround you could define your own ranges with localized labels.

To fix it within this project the labels within defaultRanges.js need to be externalized somehow.

**Comment by mkg0** [comment]
It doesn't provide localized defined range options and there is no decision supporting it or not.
You should define your own parameters to do it.

check: #214

**Comment by aafreensheik1** [comment]
The locale of the DateRange component can be set by importing the language from 'moment/locale/ru' ('ru' in this case)

```
import React from "react";
import ReactDOM from "react-dom";
import { DateRange } from "react-date-range";
import ru from 'moment/locale/ru';
import "./styles.css";

function App() {
  return (
    <div className="App">
      <DateRange locale={ru} />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
![image](https://user-images.githubusercontent.com/59209323/125732008-2198c6f3-4230-4d04-8d28-cd287143f632.png)

**Comment by chrhi** [comment]
should i run npm i moment ?
