### ISSUE TITLE
There is no option to start the week from a specific day.

### ISSUE THREAD

**Issue by Praneetha-CK** [Adphorus/react-date-range#237]
## Subject of the issue
There is no option to start the week from a specific day. By default, it starts from Sunday.  There must be an option to change it let's say Monday.

## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.

## Environment
Package Version:
React version:
Node version:
Browser:

**Comment by mkg0** [comment]
Hi @Praneetha-CK 

We don't allow to manipulate first day of week. You should define a locale for changing the default locale behaviours.

```js
import enGb from 'react-date-range/dist/locale/en-GB';

<DateRangePicker
  {...props}
  locale={enGb}
/>
```
