### ISSUE TITLE
There is no option to change the navigation arrow icons

### ISSUE THREAD

**Issue by Praneetha-CK** [Adphorus/react-date-range#238]
## Subject of the issue
There is no option to change the navigation arrow icons. I would like to use my own left and right arrow icons. How do I do that?
 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.

## Environment
Package Version:
React version:
Node version:
Browser:

**Comment by mkg0** [comment]
Hi @Praneetha-CK 

You can use `navigatorRenderer` in order to change arrows.

**Comment by Praneetha-CK** [comment]
That would require me to write my own view and logic for the dropdown. I do not want that. how can I only change the icon and leave everything as  it is using navigatorRenderer?
