### ISSUE TITLE
Unable to minimize calendars and only show the date display

### ISSUE THREAD

**Issue by tomcorbett** [Adphorus/react-date-range#240]
First of all thank you so much for this library it's awesome, saved me so much time!

This may not be something that makes sense especially as multiple ranges are supported but just wanted to throw this out there...

## Expected behavior
E.g. on most date range pickers the default (or optional) behavior is to be minimized by default apart from 2 inputs showing the current dates.
Once the user clicks on either field it shows the date range picker and once the user selects a range it minimizes again.

I see a few options I can do to workaround but was thinking it would be a good config option or maybe expose a method to show/hide everything but the date display component:

## Think I can work around by
- Add wrapper class of something like calendarOpen / calenderClosed
- Update CSS to hide rdrDefinedRangesWrapper, rdrMonthAndYearWrapper, rdrMonths and set width
- onChange behavior to only hide if the startDate and endDate are not equal

Perhaps the reason the demo includes two additional text inputs is because of this and it's expected that we handle this ourselves by just showing and hiding the whole thing?

**Comment by mkg0** [comment]
Hi @tomcorbett,

Our decisiveness about is, not  to provide show/hide functionalities. This library's plan is just providing date related components to allow developers to compose them. Every project has different demands and we think the best way to making it is keeping it modulated.

Currently, we provide `Calendar`, `DateRange`, `DefinedRange` and `DateRangePicker`(that is composed version of DateRange and DefinedRange).

Also for the next steps; it will provide inputs(for representing dates, date ranges and times), a time picker and stateful box with `confirm`/`cancel` buttons. But at the end of the day, hiding calendar will be users' own responsibility.

**Comment by tomcorbett** [comment]
OK understood @mkg0 completely makes sense, thank you!!

**Comment by Chun-Lin** [comment]
Hi @mkg0  @tomcorbett 

I have a similar question, but still don't understand why calendar doesn't have hide/show functionality.

Since `DateInput` component has been used in `Calendar` component, and there is a prop can hide `DateInput`, I think `Calendar` should have hide/show functionality?

I've tried some workaround solutions to try hide/show based-on the state of my custom date input fields, but I don't know which prop in `Calendar` (or `DateRange`) I should use to notify the custom input fields that date ranges has been set and Calendar component can be hide. Is there anything I miss?

Thanks!

**Comment by phutngo** [comment]
> Hi @mkg0 @tomcorbett
> 
> I have a similar question, but still don't understand why calendar doesn't have hide/show functionality.
> 
> Since `DateInput` component has been used in `Calendar` component, and there is a prop can hide `DateInput`, I think `Calendar` should have hide/show functionality?
> 
> I've tried some workaround solutions to try hide/show based-on the state of my custom date input fields, but I don't know which prop in `Calendar` (or `DateRange`) I should use to notify the custom input fields that date ranges has been set and Calendar component can be hide. Is there anything I miss?
> 
> Thanks!

Totally agree with you!

It's already composable, why not have the functionality to hide the calendar and only show DateInput. The usage of showing only DateInputs and then expanding the rest (such as Calendar, DefinedRanges etc) is so common. Currently, from an end-user pov, either you have to see the whole giant thing or it is hidden behind a button.
