### ISSUE TITLE
Support Hungarian 🇭🇺

### ISSUE THREAD

**Issue by balazsorban44** [Adphorus/react-date-range#245]
## Subject of the issue
Support Hungarian 🇭🇺
 
## [BUG] Bug Reproduce Steps
- The newest version does not contain Hungarian

## [BUG] Expected behaviour
- Hungarian locale is available

## Environment
Package Version: newest
React version: newest
Node version: stable
Browser: all

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0) Thank you for pointing it out. I'm closing this.
