### ISSUE TITLE
option to specify row numbers

### ISSUE THREAD

**Issue by balazsorban44** [Adphorus/react-date-range#252]
## Subject of the issue
Right now, there are arbitrary rows rendered, depending on how many placeholder days are added.
 
## [FEATURE REQUEST]
Add a prop, for example:
```js
rows={Number}
```
That renders the given amount of rows.
Alternatively, a `Boolean` would be enough as well:
```js
fixedHeight={Boolean}
```
If set to `true` it renders 6 rows, otherwise the current behavior.

The goal is to prevent the calendar's height to change, to stop jumps. Especially less annoying on mobile devices.

## Environment
Package Version: future release
React version: all
Node version: all
Browser: all

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0) Thank you for pointing it out. I'm closing this.
