### ISSUE TITLE
TypeError: locale.localize.months is not a function

### ISSUE THREAD

**Issue by Ionut-Milas** [Adphorus/react-date-range#258]
## Subject of the issue
I am trying to add enGB locale.
I simply installed the date-fns lib, and the datepicker crashes with the above error
 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.
I just added "date-fns": "2.0.0-alpha.25",

## [BUG] Expected behaviour
It should not crash

## Environment
Package Version: "^1.0.0-beta"
React version: 16.5.2
Node version: 10
Browser: Chrome

**Comment by VIMGAS** [comment]
Same problem here...

Tried to use pt-BR locale and the exact same error ocurred.

**Comment by laminh711** [comment]
For anyone still wondering, try downgraded date-fns version to 2.0.0-alpha.7. It works for me.

**Comment by mohsensaremi** [comment]
@laminh711 
version `2.0.0-alpha.7` does not have my locale
I need `faIR` locale

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release (1.1.0). Now, date-fns is loaded as a peer dependency and you can use versions between 2.0.0 and the latest. I'm closing this.
