### ISSUE TITLE
Failing to install via yarn

### ISSUE THREAD

**Issue by vitorboccio** [Adphorus/react-date-range#264]
## Subject of the issue
Cannot install the package via yarn.
It throws an error "Error: [ERROR] You need npm version @>=5 but you have 3.5.2"
3.5.2 is the most recent npm version
 
## Environment
Node version: 8.10.0
NPM version: 3.5.2

**Comment by jeffyyyy** [comment]
npm v3 is so old, upgrade plz

**Comment by onurkerimov** [comment]
I'm closing this, since it has been answered.
