### ISSUE TITLE
firstDayOfWeek help!!

### ISSUE THREAD

**Issue by ricardosaumeth** [Adphorus/react-date-range#265]
## Subject of the issue
Describe your issue here.

He there. 
I am trying to set the start date of the calendar to be Monday. I set the firstDayOfWeek={1} and no change at all.
 I have used version 1.0.0-beta and 0.9.4

Any ideas.

Thanks
 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.

## Environment
Package Version: 1.0.0-beta and 0.9.4
React version: 16.5.0
Node version: v8.11.3
Browser: Chrome

**Comment by vitorboccio** [comment]
Try 'startOfWeek' instead.

**Comment by ricardosaumeth** [comment]
Thanks for your answer. I set startOfWeek={1} / startOfWeek="Monday" and other numbers and no luck. Thanks
