### ISSUE TITLE
 how can i set this calendar to open on input click

### ISSUE THREAD

**Issue by seersol92** [Adphorus/react-date-range#266]
##how can i set this calendar to open on input click

**Comment by suncn** [comment]
you can placeholder calendar in one div element, to set the div element display or hidden.

**Comment by onurkerimov** [comment]
I'm closing this since it has been answered.

**Comment by andrei-dascalu** [comment]
just a suggestion: perhaps add an example of how to do this in the docs ?

**Comment by MatiasManevi** [comment]
> ##how can i set this calendar to open on input click

[solution](https://github.com/Adphorus/react-date-range/issues/364)
