### ISSUE TITLE
Is this package no longer under active development?

### ISSUE THREAD

**Issue by bsdahl** [Adphorus/react-date-range#275]
I noticed the last commit was August 2018. Is this package no longer under active development?

Anything I can do to help?

**Comment by ryanmauer** [comment]
I have the same question. Is there any active development planned for this package?

**Comment by mortargrind** [comment]
No, the project is not abandoned. 

But clearly the main contributors do not have the time to actively respond the issues & feature requests. We recently began to implement some small features but of course that's not enough and does not solve users' urgent requirements. 

If you've found bugs or have feature requests and if you think you have the time to open a PR, we'll gladly review them :) 

Hopefully, in the near future, we as an organization will find more resources to be able to actively contribute to the project again. 

Hope that this answer clears some of your concerns.

**Comment by bsdahl** [comment]
@mortargrind thanks for the update! Everyone here appreciates your work on this project.

**Comment by consense** [comment]
Wondering the same seeing the amount of open PRs. Also appreciating all the effort obviously :-)
