### ISSUE TITLE
disabledDates not working

### ISSUE THREAD

**Issue by francescovenica** [Adphorus/react-date-range#276]
## Subject of the issue
I'm trying to disable days passing `disabledDates={[ new Date() ]}` as props
 
```
            <DateRange
              onChange={this.handleRangeChange.bind(this, 'dateRangePicker')}
              disabledDates={[ new Date() ]}
              showSelectionPreview={true}
              moveRangeOnFirstSelection={false}
              className={'PreviewArea'}
              months={2}
              ranges={[this.state.dateRangePicker.selection]}
              direction="horizontal"
              showDateDisplay={false}
            />
```

## [BUG] Bug Reproduce Steps
After adding the disabled data I can select it without any problem

## Environment
Package Version: 1.0.0-beta1/1.0.0-beta2
React version: 16.4.1
Node version: 8:11:4
Browser: chrome

**Comment by francescovenica** [comment]
Just found the problem, to disable a dates you need to format them `formatDateDisplay`...maybe we should add this on readme

**Comment by Roconda** [comment]
I ran into the same issue. Do you have a working example?

**Comment by PinkFLoyd92** [comment]
I am having the same issue. Can u guys tell me how you work this out? :+1:

**Comment by mingjunlu** [comment]
I also ran into this one. Anyone figured out how to solve this?

**Comment by bleachdugu** [comment]
@mingjunlu  the temporary solution is #231,  clone the master branch and build dist our own. 
But I thinks we should publish it to npm asap. Or you could fork the Repo and publish to your own package manage space

**Comment by mingjunlu** [comment]
> @mingjunlu the temporary solution is #231, clone the master branch and build dist our own.
> But I thinks we should publish it to npm asap. Or you could fork the Repo and publish to your own package manage space

@bleachdugu Get it! Thanks for your help 👍
