### ISSUE TITLE
Use Placeholders instead of actual text in select box for input ranges

### ISSUE THREAD

**Issue by twheys** [Adphorus/react-date-range#278]
## Subject of the issue
The input ranges field (_n_ days up to today) a "-" character is used as a placeholder. Instead of using an html placeholder attribute on the input, a literal "-" is inserted into the input box. Please change this to use the html placeholder attribute, otherwise the user is forced to manually remove the placeholder text.

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.0.1) Thank you for pointing it out. I'm closing this.

**Comment by tusherpisqr** [comment]
i have updated the latest one seems the placeholder is not there . its input thing which replace upon entering value . there is a bug to it .if i enter some value it always start with 1 . any solution ???
