### ISSUE TITLE
Allow dates to be entered manually by typing in the start/end input fields

### ISSUE THREAD

**Issue by twheys** [Adphorus/react-date-range#279]
## Subject of the issue
The input fields above the calendar which display the selected dates are selectable but text cannot be manually typed into them. Please change this so a date can be typed as an alternative to selecting it in the calendar. This would be much easier to use for large periods that are not available as static ranges.

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0)
We merged @vladaspasic's PR on this.
Thank you for pointing it out. I'm closing this.
