### ISSUE TITLE
Cannot resolve date-fns

### ISSUE THREAD

**Issue by eL-HaXo** [Adphorus/react-date-range#283]
## Subject of the issue
I have installed react-date-range and the latest (v1.30.1) version of the date-fns package. When I import the date range picker I get multiple errors that various date-fns methods cannot be resolved. Below is an example of the errors. I tried aliasing date-fns in my webpack config but that didn't work. Any help would be appreciated.
 
## Example Error
`client:168 ./node_modules/react-date-range/dist/components/DayCell.js Module not found: Error: Can't resolve 'date-fns/startOfDay'`

## Environment
Package Version: react-date-range@1.0.0-beta
date-fns Version: 1.30.1
React version: 16.5.2
Node version: 11.3.0
Browser: Chrome

**Comment by jeffyyyy** [comment]
"date-fns": "2.0.0-alpha.7", required date-fns version is v2...

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0)
Now this plugin takes date-fns as a peerDependency and can work with a wide range of versions (2.0.0 to the latest)
Thank you for pointing it out. I'm closing this.
