### ISSUE TITLE
DateRangePicker is not exported correctly

### ISSUE THREAD

**Issue by vasilevach** [Adphorus/react-date-range#284]
## Subject of the issue
DateRangePicker gives a default "not exported correctly" error in the console:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
 
## [BUG] Bug Reproduce Steps
You need "react": "^16.8.0". Just import it like in your demo:

```
import { DateRangePicker } from 'react-date-range';

<DateRangePicker direction="horizontal" />
```

I do not reproduce this bug with Calendar or DateRange

## [BUG] Expected behaviour
Not to trow the "not exported" error

## Environment
Package Version: npm 6.4.1
React version: 16.8.0
Node version: 10.15.1
Browser: not related, but Chrome 72.0.3626.119

**Comment by ranjan-malav** [comment]
Facing the same issue. Can you explain what was the reason?

**Comment by gota1993** [comment]
Same problem. Please fix it

**Comment by Ajayghoshm** [comment]
Any fix?
