### ISSUE TITLE
Date-fns dependency type

### ISSUE THREAD

**Issue by nickinnon** [Adphorus/react-date-range#294]
## Subject of the issue
Right now the package has a core dependency on an alpha version of date-fns.
Two issues:
1) Does this package use specific features in the new release of date-fns that the core dependency couldn't be downgraded to the most stable release?
2) Can date-fns be a peer dependency so this package does not include it's own version of date-fns when imported into a project?

Admittedly, I'm no expert on NPM's dependency model, so I could be misunderstanding something.

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0) 
Now this plugin takes date-fns as a peerDependency and can work with a wide range of versions (2.0.0 to the latest)
Thank you for pointing it out. I'm closing this.
