### ISSUE TITLE
Ability to configure the weekdays format

### ISSUE THREAD

**Issue by bmaximilian** [Adphorus/react-date-range#299]
## Subject of the issue
You cannot configure the format of the weekdays of a month.

## Expected behaviour
Weekdays format can be configured with a prop

## Pull Request
https://github.com/Adphorus/react-date-range/pull/256

**Comment by dtalaba** [comment]
Hi @bmaximilian, do you know when this pull request will be merged ? Thanks !

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0)
If I had seen your PR before, I would merge it. It has conflicts since file structure of the project is changed.
Thank you for pointing it out, and solving. I'm closing this since the same solution is in the latest release.
