### ISSUE TITLE
Doesn't work with IE11

### ISSUE THREAD

**Issue by snaptravel-eng** [Adphorus/react-date-range#300]
## Subject of the issue
Does not work with IE11
 
## [BUG] Bug Reproduce Steps
Open http://adphorus.github.io/react-date-range/ on IE11
Entire page is blank

## [BUG] Expected behaviour
Should work on IE11

## Environment
Package Version:
React version:
Node version:
Browser: IE11

**Comment by jayjongcheolpark** [comment]
I checked legacy version was working on IE11. I saw the history that proxy was replaced to support on IE11. Let me know if we need any polyfill for IE11.

**Comment by maxpaynestory** [comment]
Add below code on top of index.js of your react app. These are the polyfills for IE 11.

```javascript
if (window.NodeList && !NodeList.prototype.forEach) {
    NodeList.prototype.forEach = function (callback, thisArg) {
        thisArg = thisArg || window;
        for (var i = 0; i < this.length; i++) {
            callback.call(thisArg, this[i], i, this);
        }
    };
}

if (!Element.prototype.matches) {
    Element.prototype.matches = Element.prototype.msMatchesSelector ||
        Element.prototype.webkitMatchesSelector;
}

if (!Element.prototype.closest) {
    Element.prototype.closest = function (s) {
        var el = this;

        do {
            if (el.matches(s)) return el;
            el = el.parentElement || el.parentNode;
        } while (el !== null && el.nodeType === 1);
        return null;
    };
}
```

**Comment by onurkerimov** [comment]
I'm closing this, since it has been answered.
