### ISSUE TITLE
Scroll Doesn't work as shown in the example

### ISSUE THREAD

**Issue by davidychow87** [Adphorus/react-date-range#304]
## Subject of the issue
I followed the example for the 'Vertical Infinite' date picker example: https://github.com/Adphorus/react-date-range/blob/master/demo/src/components/Main.js

The scrollling doesn't seem to work:

`
            <div>
                <DateRangePicker
                    onChange={this.handleRangeChange.bind(this, 'dateRangePickerI')}
                    months={1}
                    minDate={new Date('2018-04-02')}
                    maxDate={new Date()}
                    direction="vertical"
                    scroll={{ enabled: true }}
                    ranges={[this.state.dateRangePickerI.selection, this.state.dateRangePickerI.compare]}
                />
            </div>
`

The month stays the same without changing
 
![image](https://user-images.githubusercontent.com/22185727/60139293-38f9e080-9762-11e9-8dd2-8a97ce0acddf.png)

## [BUG] Bug Reproduce Steps
React version: 16.6.3

## [BUG] Expected behaviour
The month should change as you scroll.

## Environment
Package Version: ^1.0.0-beta
React version: 16.6.3
Node version:
Browser: Chrome

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release. (1.1.0)
Thank you for pointing it out. I'm closing this.

**Comment by hothvictor** [comment]
> This issue is resolved in the latest release. (1.1.0)
> Thank you for pointing it out. I'm closing this.

the latest version is 1.0.3..
