### ISSUE TITLE
Package does not install all listed components?

### ISSUE THREAD

**Issue by aymather** [Adphorus/react-date-range#312]
## Subject of the issue
Describe your issue here.
 
## [BUG] Bug Reproduce Steps

run `npm install --save react-date-range`

Look in the `node_modules` folder and the DateRangePicker is not imported.

Also most of the properties are not working correctly for me even when I use DateRange which is imported.

## Environment
Package Version:
React version:
Node version:
Browser:

**Comment by gota1993** [comment]
This problem still occur. Any update about this?

**Comment by onurkerimov** [comment]
Not all the components are exported in the root, but you can export all of them by specifying the folder.
For example:

```js
export DayCell from 'react-date-range/components/DayCell';
```
