### ISSUE TITLE
No option to turn off predefined date selectors

### ISSUE THREAD

**Issue by danatinxeption** [Adphorus/react-date-range#313]
## Need to hide the predefined date selectors
I built my own pre defined date selector and it has actions that isn't fit into the library's structure. The only way I can think of is pass in an empty array for the staticRanges and inputRanges but I still need to use css to hide the element.

**Comment by poom** [comment]
use `DateRange`  - See example in `RangePicker` section 

> https://github.com/Adphorus/react-date-range/blob/master/demo/src/components/Main.js

**Comment by onurkerimov** [comment]
I'm closing this, since it's answered.
