### ISSUE TITLE
How to disabled all weekend in this calendar

### ISSUE THREAD

**Issue by bleachdugu** [Adphorus/react-date-range#314]
## Subject of the issue
How to disabled all weekend in this calendar, I want to disabled weekend, but I can't pass all the weekend date to the disabledDates props (since its a Date object of Array)
 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.

## [BUG] Expected behaviour
Expect a new Props to disable weekend or improve disabledDates props

## Environment
Package Version:
React version:
Node version:
Browser:

**Comment by onurkerimov** [comment]
You can use the following helper function to calculate all weekends between two dates
```js
import { addDays, isWeekend } from 'date-fns';

function calcWeekends(startDate, endDate) {
    if (startDate > endDate) return false;
    var date  = startDate;
    var dates = [];

    while (date < endDate) {
        if (isWeekend(date)) dates.push(new Date(date));
        date.setDate( date.getDate() + 1 );
    }

    return dates;
}

const disabledDates = calcWeekends(new Date(), addDays(new Date(), 100))
```
Then, simply set `disabledDates={disabledDates}` in the component you want to use.
