### ISSUE TITLE
Date's shift's when we use moment.tz

### ISSUE THREAD

**Issue by sachinkondana** [Adphorus/react-date-range#327]
## Subject of the issue
Date's shift's when we use moment.tz
 
## [BUG] Bug Reproduce Steps
During the launch of my app, I set my timezone to user timezone.

moment.tz.setDefault(tz);

Now when I pass any moment dates to 'DateRangePicker' it behaves weird. How can I enforce the plugin to follow my moment timezone?

[![Edit gifted-snow-vyvjw](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-snow-vyvjw?fontsize=14)

![date_issue](https://user-images.githubusercontent.com/33169894/65239590-fcd5e200-dafc-11e9-83ce-f89016b2936e.png)

**Comment by mesvil7** [comment]
You can turn the startDate, endDate in the onChange callback to a moment object.
Something like this:

const selectionRange = {
    startDate: moment().startOf("day"),
    endDate: moment().endOf("day"),
    key: "selection"
  }

const [rangeDates, setRangeDates] = useState(selectionRange)

const handleOnChange = payload => {
    const { startDate, endDate } = payload.selection

    setRangeDates({
      ...rangeDates,
      startDate: moment(startDate),
      endDate: moment(endDate),
    })
  }

<DateRange
        ranges={[rangeDates]}
        onChange={handleOnChange}
      >

**Comment by sachinkondana** [comment]
The problem here was timezone, the date-range-picker takes system zone, not the moment zone. The workaround I did was, just remove the hours and zone values from the dates. This fixed my issue.
