### ISSUE TITLE
componentWillReceiveProps will be removed in React 17

### ISSUE THREAD

**Issue by sirbully** [Adphorus/react-date-range#331]
## Subject of the issue
Our team is using the Calendar component. Received a warning that this component is using the deprecated lifecycle method componentWillReceiveProps.

[Legacy React Component Documentation](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops)

## Environment
Package Version: 0.9.4
React version: 16.8.6
Node version: 10.15.0
Browser: Google Chrome

**Comment by onurkerimov** [comment]
This issue is resolved in the last merged PR. Thanks for pointing it out. I'm closing this.
