### ISSUE TITLE
dateDisplayFormat, how to use it in DateRangePicker?

### ISSUE THREAD

**Issue by alukaszew89** [Adphorus/react-date-range#336]
I dont't really know how to use this property  

Could you please describe it on the example ?

Thanks

**Comment by gudapraveenkumar** [comment]
<DateRange
              onChange={(item) => handleChange(item)}
              months={2}
              ranges={dateTimeRange}
              dateDisplayFormat={'yyyy-MM-dd HH:mm'}
              direction="horizontal"
              editableDateInputs={true}
            />
