### ISSUE TITLE
if scroll.enabled===true, then DateRange won't initially show the month of selected date range! it shows Feb 1920

### ISSUE THREAD

**Issue by mahesha-perpetualny** [Adphorus/react-date-range#339]
## DateRange won't initially show the month of selected date range! it shows Feb 1920
same as https://github.com/Adphorus/react-date-range/issues/190 but for DateRange
 
![image](https://user-images.githubusercontent.com/60252612/73967323-ae0ad680-493d-11ea-970f-940f8fc3e028.png)

## [BUG] Bug Reproduce Steps
import { DateRange } from "react-date-range";

export default function dateRange() {
    return (<DateRange
        showDateDisplay={false}
        direction="vertical"
        scroll={{ enabled: true }}
        showMonthAndYearPickers={false}
    />);
}

## [BUG] Expected behaviour
It should show the selected Month.

## Environment
Package Version:^1.0.0-beta
React version:^16.12.0
Node version:6.13.7
Browser: Chrome

**Comment by onurkerimov** [comment]
As far as I can see the same issue does not occur in the latest version (1.0.1) I'm closing this.
