### ISSUE TITLE
Typographical error in Readme.md

### ISSUE THREAD

**Issue by wallwhite** [Adphorus/react-date-range#340]
## Subject of the issue
# Typographical error in Readme.md

In the head of the table in the "options" section
![image](https://user-images.githubusercontent.com/11584713/74042821-ec9da100-49d0-11ea-9ebd-d3480d6469f8.png)

Desctiption -> Description

**Comment by onurkerimov** [comment]
This issue is resolved in the last merged PR. Thanks for pointing it out. I'm closing this.
