### ISSUE TITLE
Incorrect year shown on DateRange header with scroll enabled.

### ISSUE THREAD

**Issue by wot48** [Adphorus/react-date-range#342]
## Subject of the issue
Incorrect year shown on DateRange header with scroll enabled when first loaded.
Year shown is from minDate, not the current year.

## [BUG] Bug Reproduce Steps

<DateRange scroll={{ enabled: true }} ... />

## [BUG] Expected behaviour
![error](https://user-images.githubusercontent.com/15217640/74165999-e8050280-4bf3-11ea-82ca-6cc5eeda99c1.png)

## Environment
Package Version: 1.0.0-beta
React version: 16.12.0
Node version: v12.13.1
Browser: Chrome

**Comment by onurkerimov** [comment]
This issue should be resolved in the last version (1.1.0).
