### ISSUE TITLE
npm package version bump issue 

### ISSUE THREAD

**Issue by AmrinderKullar** [Adphorus/react-date-range#345]
## Subject of the issue
npm package is not updated to the latest **(1.1.0)** still it is **0.9.4** 

https://www.npmjs.com/package/react-date-range

## Environment
Package Version: 0.9.4
React version: > 16
Node version: > 10
Browser: latest

**Comment by mefallit** [comment]
@AmrinderKullar npm package is updated now 🎉 

Thanks to @onurkerimov
