### ISSUE TITLE
Module not found: Can't resolve 'date-fns/locale/en-US' 

### ISSUE THREAD

**Issue by praneetha-ck-robo** [Adphorus/react-date-range#352]
## Subject of the issue
```
Failed to compile
./node_modules/react-date-range/dist/components/Calendar/index.js
Module not found: Can't resolve 'date-fns/locale/en-US' in '/Volumes/Development/NoonProjects/merchant-panel/frontend/node_modules/react-date-range/dist/components/Calendar'
```
 
## [BUG] Bug Reproduce Steps
After running `npm install` and then running `npm start`, I get this error.

## Environment
Package Version: "^1.0.3"
React version: ""^16.13.0"
Node version: v12.16.1
Browser: Chrome - Version 80.0.3987.132

**Comment by onurkerimov** [comment]
Hello. Its answered [here](https://github.com/Adphorus/react-date-range/issues/348#issuecomment-592423295). I'm closing this issue.
