### ISSUE TITLE
Not working with safari on macOS Mojave

### ISSUE THREAD

**Issue by JihadBadran** [Adphorus/react-date-range#354]
## Subject of the issue
I have used react-date-range in my app, and it's causing the app to crash on macOS Mojave Safari Version 12.1.1 (14607.2.6.1.1)

Even demo page of is cashing on safari
 
## [BUG] Bug Reproduce Steps
Just open of the page

## Environment
Package Version: V 1.0.3
React version: V 16.12.0
Node version: v11.12.0
Browser: Safari Version 12.1.1 (14607.2.6.1.1)

**Comment by sijad** [comment]
@JihadBadran did you figured out what causing this?
I have same issue with safari 13.1.1 and 14.0.1

**Comment by sijad** [comment]
it seems this issue is related to https://github.com/date-fns/date-fns/issues/1753
