### ISSUE TITLE
Can't resolve 'date-fns/locale/en-US' in eact-date-range

### ISSUE THREAD

**Issue by GaurabendwithB** [Adphorus/react-date-range#359]
Its time to update date-fns

Date range is throughing error because of date-fns
Can't resolve 'date-fns/locale/en-US' in '\node_modules\react-date-range\dist\components\Calendar'

**Comment by onurkerimov** [comment]
Hi, its answered [here](https://github.com/Adphorus/react-date-range/issues/352#issuecomment-598153160). I'm closing this issue.

**Comment by alexfornuto** [comment]
What would be the next troubleshooting step when encountering this error if `date-fns` is already installed?

**Comment by alexfornuto** [comment]
It would appear that `var _enUS = _interopRequireDefault(require("date-fns/locale/en-US"));` is not valid, as the current form of date-fns only has `/locale/en`, not `/locale/en-US`.

```
