### ISSUE TITLE
How to remove the side bar showing today yesterday to nothing

### ISSUE THREAD

**Issue by piyush97** [Adphorus/react-date-range#371]
## Subject of the issue
How to remove the side bar showing today yesterday to nothing
 
![image](https://user-images.githubusercontent.com/18229627/82362788-8215eb80-9a2a-11ea-9240-f44e07cb120a.png)

**Comment by shivam-baghla** [comment]
use <DateRange /> instead of <DateRangePicker />

**Comment by chrisclausen90** [comment]
Or set staticRanges={[]}

**Comment by piyush97** [comment]
Thanks
