### ISSUE TITLE
Will react-date-range work on IE11

### ISSUE THREAD

**Issue by PreetiBansalPP** [Adphorus/react-date-range#382]
## Subject of the issue
Describe your issue here.
I ma using DateRange of react-date-range. it works beautifully on chrome , firefox, but on IE as soon as I try to render calendar, it gives object does not supports findIndex method as below -
![Screen Shot 2020-06-25 at 1 00 15 PM](https://user-images.githubusercontent.com/19339461/85642048-687c5980-b6e4-11ea-8c6c-d55a91884429.png)

I tried to add a polyfill for array,findIndex in my react project, hoping it will apply to react-date-range dateRange component too. it kind of works but then changes error to uncaught error occurred, and still no rendering of calender.

 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.
Open your demo site http://adphorus.github.io/react-date-range/ in IE 11, it throws `Expected identifier` error. 

## [BUG] Expected behaviour
I won't say it should render , but my question is does is support iE 11? I am quite new to this and could not find otehr place to post my question, so juts created an issue. Apologies for that.

## Environment
Package Version: 1.0.3
React version: 16.8.0
Node version: 6.17.1
Browser: IE 11

**Comment by keremciu** [comment]
unfortunately support IE 11 would be a hard goal for the library :/
