### ISSUE TITLE
Can't resolve 'date-fns'

### ISSUE THREAD

**Issue by rusakovic** [Adphorus/react-date-range#386]
## Subject of the issue
./node_modules/react-date-range/dist/defaultRanges.js
Module not found: Can't resolve 'date-fns' in 'C:\project\node_modules\react-date-range\dist'

## Environment
Package Version: 1.0.3
React version: 16.12
Node version: 12.16
Browser: Chrome 83

How to fix it?
Thank you

Solution:
`npm install date-fns`

Should be added to docs.

**Comment by gsouf** [comment]
That's a peer deps, that's expected

**Comment by rusakovic** [comment]
Yes, thank you.
But could you add possibility to use custom components with their own style?

**Comment by keremciu** [comment]
@rusakovic yep as @gsouf wrote, it's written on readme `This plugin expects react and date-fns as peerDependencies, It means that you need to install them in your project folder.`

hope you didn't spend much time on it :/
