### ISSUE TITLE
onlyClasses is not defined

### ISSUE THREAD

**Issue by Lvfalue** [Adphorus/react-date-range#44]
when i use the DateRange component with  the property range , the browser show the error 'Uncaught ReferenceError: onlyClasses is not defined' . 

![image](https://cloud.githubusercontent.com/assets/5802036/13346740/4e9e4890-dca3-11e5-83d0-2124330d9381.png)

i find the code in PredefinedRanges.js , line 57-83 .  when i add the variate onlyClasses which is read from this.props , the component render successfully. thanks!

**Comment by burakcan** [comment]
Fixed by: https://github.com/Adphorus/react-date-range/pull/43
Will release a new minor version today.

**Comment by BenjaminRCooper** [comment]
Could we get a version bump to follow this change please @burakcan?

**Comment by burakcan** [comment]
https://github.com/Adphorus/react-date-range/issues/46#issuecomment-191785654
