### ISSUE TITLE
Calendar width issues in Firefox.

### ISSUE THREAD

**Issue by samsch** [Adphorus/react-date-range#45]
I'm testing in Firefox on Xubuntu, and it looks like the calendar width is just a touch too small to render all seven days in a row.

Screenshot of problem:

![Calendar width issue](http://i.imgur.com/Fv3GPonl.png)

**Comment by djforth** [comment]
+1

**Comment by itsterry** [comment]
+1

**Comment by binjospookie** [comment]
I  `width: 308px;` for `div.rdr-Calendar` and fix it.

**Comment by scclose** [comment]
+1
I set the padding in the theme of the calendar to fix, decremented the horizontal padding by one like: 
theme={{
              Calendar       : {
                width        : '200px',
                padding      : '10px 9px'
              },
...

**Comment by xingyesh** [comment]
+1

**Comment by socker210** [comment]
+1
