### ISSUE TITLE
Uncaught ReferenceError: onlyClasses is not defined (0.2.3)

### ISSUE THREAD

**Issue by swillard-r7** [Adphorus/react-date-range#46]
Hi there. I upgraded from 0.2.2 to 0.2.3 and I'm getting the following error:

`Uncaught ReferenceError: onlyClasses is not defined`

```
Uncaught ReferenceError: onlyClasses is not defined(anonymous function) @ PredefinedRanges.js?
23ea:77renderRangeList @ PredefinedRanges.js?23ea:66render @ PredefinedRanges.js?
...
```

Any ideas?

**Comment by BenjaminRCooper** [comment]
I get the same issue.

**Comment by BenjaminRCooper** [comment]
Never mind #44 fixes this, apologies for not observing closed issues first.

**Comment by BenjaminRCooper** [comment]
I think a version bump needs to happen, as stated in #44.

**Comment by LoicUV** [comment]
yup, much needed :+1:

**Comment by burakcan** [comment]
Done :+1: sorry for delay :(

**Comment by LoicUV** [comment]
:heart:
