### ISSUE TITLE
Addition of apply and cancel links

### ISSUE THREAD

**Issue by BenjaminRCooper** [Adphorus/react-date-range#47]
Thinking in terms of an enhancement. It would make sense as the onChange event fires on change of any value but when picking a range, having an apply event seems more suitable.

**Comment by burakcan** [comment]
We're using it at Adphorus exactly this way :) but we think that this is an application feature; not this component's. Maybe @strada or @fatiherikli can share the way we use with a code example.

**Comment by BenjaminRCooper** [comment]
Would be awesome if so @strada, @fatiherikli. Would be much appreciated.
