### ISSUE TITLE
Show prices for each day in calendar

### ISSUE THREAD

**Issue by anticol** [Adphorus/react-date-range#476]
I would like to show price for each day in calendar. I have object with date and price, each day can have different price. Is there a way to do it ?

Something like that:
![image](https://user-images.githubusercontent.com/11396592/119995668-203d7980-bfce-11eb-8843-3a302dafce25.png)

Thanks a lot!

**Comment by kamyar** [comment]
Please see #483 which will handle this

**Comment by Satyam580** [comment]
@anticol 
Me also facing same issue how to handle day cell and to add price.
if you fixed that issue? help me

**Comment by anticol** [comment]
@Satyam580 my problem was passing prop value={watch('inputName')}, when I removed it, it worked

**Comment by anticol** [comment]
@Satyam580 i created my own calendar, originally forking this repo

**Comment by EderJunior07** [comment]
Anyone can help me to add the prices 
please?

**Comment by sownthariya-mahe** [comment]
can you help me to set this price on date
