### ISSUE TITLE
Document Min & Max Props

### ISSUE THREAD

**Issue by BenjaminRCooper** [Adphorus/react-date-range#48]
I noticed as part of v2.0, min and max props were added but the documentation wasn't updated to show this.

Just thought I'd put a note in as it may be useful to a lot of people and with the documentation not containing these changes, it may have went unnoticed.

**Comment by alexjesp** [comment]
I also came to the repo not realising that these props existed. After digging it appears that `minDate` / `maxDate` don't support `Date` instances. Any reason for this?

**Comment by gabrielflorit** [comment]
Took me a while to figure it out, but `minDate/maxDate` should be `moment` instances.

**Comment by burakcan** [comment]
https://github.com/Adphorus/react-date-range/pull/74
