### ISSUE TITLE
Add disabled date range

### ISSUE THREAD

**Issue by dcworldwide** [Adphorus/react-date-range#49]
It would be great if we could define a disabled date range, like http://amsul.ca/pickadate.js/date/#disable-dates

```
$('.datepicker').pickadate({
  disable: [
    { from: [2016,2,14], to: [2016,2,27] }
  ]
})
```

I would like to force users to select dates within a pre-defined date range.

**Comment by burakcan** [comment]
Actually; we have min-max date option but it's not documented yet. Please see: https://github.com/Adphorus/react-date-range/pull/34

**Comment by dcworldwide** [comment]
Aah 👌.  Will test
