### ISSUE TITLE
Update min and max calendars for date range

### ISSUE THREAD

**Issue by sunjay** [Adphorus/react-date-range#50]
Let's say I have the "Range Picker (Predefined Ranges)" example on the [Examples page](http://adphorus.github.io/react-date-range/). Instead of Last 30 days, I define a range called "Last 6 Months". When I use it, the right calendar goes to today's date and the left calendar gets completely highlighted since it is within the last 6 months range.

This doesn't actually show the user what start date was selected since it isn't on the left calendar. It's several months before it.

When updating either calendar, it should automatically go to the month and year that was selected. There is no way to link a calendar to initially showing its selected day/date. 

---

Another possible example of this is a predefined range for a set of specific dates in the past or future. For example I could have a predefined range called "Summer (2015)" which has a start date of July 1, 2015 and an end date of August 30, 2015. The date range picker should allow for some way to show those two dates highlighted in both of the calendars shown in my date range control.

---

Image: 
![ss 2016-03-22 at 02 19 49](https://cloud.githubusercontent.com/assets/530939/13962839/2b313526-f039-11e5-8145-bae10d15e206.png)

This is how it looks when your start date is not on the two displayed calendars. The current calendars do not automatically move to their selected date when that date is first selected.

**Comment by tahaemin** [comment]
@sunjay how did you solve your problem?

**Comment by sunjay** [comment]
It's been about a year so I don't really remember but I think I ended up just using another component. Sorry I can't be of more help but it's been a while since I posted this issue.

**Comment by mikeroelens** [comment]
@tahaemin setting rangedCalendars={true} on DateRange component should do the trick!

**Comment by Branded89** [comment]
@mkg0 
I know this issue is closed and signed with "Deprecated version" .. but what are the chances this will 
be enabled/added to the current DateRange functionality? Where the first calendar display the year and month of the selected startdate, and second calendar displays the year and month of the selected enddate, so the user will actually see both, startdate and enddate when they are not in adjecent months.
