### ISSUE TITLE
GPL licensing

### ISSUE THREAD

**Issue by florian** [Adphorus/react-date-range#54]
Is it really necessary to use GPL as a license? Right now every application that uses this component would [need to be open sourced](https://programmers.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application). As much as I love open source, this isn't always possible.

How about switching to the MIT license?

**Comment by jacobrask** [comment]
I strongly agree about the license change, but this is not quite correct:

> Right now every application that uses this component would need to be open sourced. 

It only applies if you *distribute* your software. 

See [these](http://programmers.stackexchange.com/questions/131264/what-constitutes-distributing-for-lgpl-v3) [questions](http://programmers.stackexchange.com/questions/132485/does-a-website-running-modified-gpl-software-have-an-obligation-to-release-their) to decide for yourself whether or not you will distribute your software, or just use the software to provide a service.

**Comment by florian** [comment]
Oh yes, you're right about that :)
However I still think that this will prevent a lot of people from using this library and that it should be changed to something more reasonable.

**Comment by orius123** [comment]
I also think MIT is better, anyways the file name has a typo should be `LICENSE` and not `LICENCE`

**Comment by hamfz** [comment]
Is there any update on switching the licensing here? I was interested in using this but the above concerns have prevented me.

**Comment by burakcan** [comment]
Hi all, we were a bit busy for a long time; so we couldn't look at the issues and pull requests, sorry for it. I will start cleaning up these.

For the licence topic; we didn't think too much about licencing while publishing the library (actually, it was my onboarding project at adphorus :) ). I will update the licence to MIT.

**Comment by apucacao** [comment]
Hey there,

Are you still planning on updating the license?

Thanks!

Alexis

**Comment by burakcan** [comment]
Switched to mit
