### ISSUE TITLE
Today indication?

### ISSUE THREAD

**Issue by DanielAviv1** [Adphorus/react-date-range#58]
Hi,

I needed to have some color indication on the today day cell,
I noticed that only the today day cell has a "undefined" className so I added some css selectors,
It works fine but.. I'm guessing that's a bug and it will not stay that way in future versions.

Is there any elegant way of custom theming only the current day cell than this one?
And thanks you all for a useful component.
Cheers :)

**Comment by Mizzade** [comment]
You can add your own custom theming via props. To highlight `today` for example, you can write:
`DayToday: {
  background: '#00CC00'
}
`

**Comment by mberhorst** [comment]
The current day has the still the class 'undefined'. Is there a version upcoming when this is fixed? For the time being I will use this class to add some custom styling. Because the DayToday styling is not visible when today is part of a selection in the DateRange selector.

**Comment by mkg0** [comment]
Fixed in the new version
