### ISSUE TITLE
Navigate calendar view to selected range (start/end)

### ISSUE THREAD

**Issue by arvindkumarc** [Adphorus/react-date-range#60]
``` js
<DatePicker startDate={this.props.startDate} endDate={this.props.endDate} />
```

It would be better if we navigate the calendar to display the corresponding selected date.

**Comment by andrewheppner** [comment]
Any word on how this might be possible? For the calendars to navigate to the corresponding date range when the selected date changes? @arvindkumarc did you figure out a way to do this?
