### ISSUE TITLE
How to support multi language

### ISSUE THREAD

**Issue by river-lee** [Adphorus/react-date-range#61]

**Comment by river-lee** [comment]
Moment supports multiple languages `moment.lang('zh-cn');`  "React-date-range" how to support?

**Comment by sonhgc00016** [comment]
You can change the language of moment on componentWillMount in your component and React-date-range automatic apply language of moment.

**Comment by mkg0** [comment]
localization completely reworked, check out https://github.com/Adphorus/react-date-range/blob/master/CHANGELOG.md
