### ISSUE TITLE
Passing dates in from state causes onChange twice

### ISSUE THREAD

**Issue by jcreamer898** [Adphorus/react-date-range#65]
So, maybe this isn't the right way to do this so if it isn't, please correct me.

``` jsx
import * as React from "react";
import { render } from "react-dom";
import { DateRange } from "react-date-range";

interface IMyComponentState {
  startDate: Date;
  endDate: Date;
} 

class MyComponent extends React.Component<{}, {}> {
  state: IMyComponentState;

  constructor() {
    super();

    this.state = {
      startDate: new Date(),
      endDate: new Date(),
    };

    this.handleChange = this.handleChange.bind(this);
  }
  handleChange(dates) {
    console.log(dates);

    this.setState({
      startDate: dates.startDate,
      endDate: dates.endDate, 
    });
  }
  render() {
    return (
      <div>
        <DateRange
          startDate={this.state.startDate}
          endDate={this.state.endDate}
          onChange={this.handleChange}
        />
      </div>
    );
  }
}

render(<MyComponent />, document.getElementById("app"));
```

I figured I could pass in dates from my state. However, when I do this, clicking on dates causes the `onChange` to fire twice.

I figure it's because I noticed that the onChange fires both from an onClick AND from a willReceiveProps.

Has anyone ran into this before? I'm trying to figure out how else to maintain the currently selected dates in state so that when I close and open the calendar in my UI, it'll maintain the selected dates.

Thanks!

**Comment by jcreamer898** [comment]
Here's an example here... https://jcreamer898.github.io/typescript-webpack-react/

**Comment by jakeorr** [comment]
I'm having the same issue.

**Comment by jakeorr** [comment]
@jcreamer898 did you find a way around this?

**Comment by jcreamer898** [comment]
Nope. Ended up using https://github.com/airbnb/react-dates/.

**Comment by jakeorr** [comment]
Ah, that should work for me also. Thanks!

**Comment by elitan** [comment]
I am having the same issue, any suggestions for resolving this, except changing to another react component?

**Comment by mkg0** [comment]
fixed in the new version
