### ISSUE TITLE
Highlight range on hover

### ISSUE THREAD

**Issue by lakshyaranganath** [Adphorus/react-date-range#66]
Great repo first off! 😄 
Just wondering if there is support for highlighting the range of dates from the selected startDate to before actually selecting endDate.

Example:
I select 16th as startDate
I hover over to 20th and there is a range 'light highlight' from 17th to 20th
I move over to 22nd and the range 'light highlight' extends to 22nd
I click on 22nd as endDate and the range gets the current implementation of 'dark highlight'

**Comment by vladi160** [comment]
Try these 2  https://github.com/airbnb/react-dates and http://zippyui.com/docs/react-date-picker

**Comment by lakshyaranganath** [comment]
Yeah sadly had to switch to react-dates to get that feature support out of
the box.
