### ISSUE TITLE
Inclusive End Date w.r.t Time

### ISSUE THREAD

**Issue by kashyapakshay** [Adphorus/react-date-range#67]
For the end date, date picker now gets the datetime as "YY/MM/DD 00:00:00" and I was thinking this might be better if it was "YY/MM/DD 23:59:59" so we include the entire last day with respect to time too. In use cases where time also matters along with the date (which is something I'm working on), this could be very useful. Also, we could probably also have a property `inclusive`? That would include or exclude start and end dates.
I will work on this and submit a pull request soon, unless people think this would not be of any use.

**Comment by dysfunc** [comment]
https://github.com/Adphorus/react-date-range/commit/63cdb21bfc5250f9b9a1e077d5d0ad78317813ff

**Comment by Sailokeshg** [comment]
This is working only when we select ranges from left panel. But we manually select particular date range from calendar component, it is still shown as 00:00:00 for endDate.

**Comment by Sailokeshg** [comment]
> This should be resolved now: [63cdb21](https://github.com/hypeserver/react-date-range/commit/63cdb21bfc5250f9b9a1e077d5d0ad78317813ff)


This is working only when we select ranges from left panel. But when we manually select particular date range from calendar component, it is still shown as 00:00:00 for endDate.

I believe this answer can solve  the above problem.
In onChange function write the following lines before sending the selected range to the state of component

<DateRangePicker
onChange((selection)=>{
selection.startDate?.setHours(0, 0, 0, 0);
selection.endDate?.setHours(23, 59, 59, 999);
setState(selection)
})
/>

This will set startDate's time as 00:00:00 in every case and endDate's time as 23:59:59 .

![predefined](https://user-images.githubusercontent.com/78192722/176156933-8f6ef055-df21-4e6b-ac23-41968dd7b819.png)
![14-17](https://user-images.githubusercontent.com/78192722/176156945-a1434d68-886b-4782-82c4-8c478161d6f3.png)
