### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by imcrthy** [Adphorus/react-date-range#85]
The current version on NPM is 0.9.0, yet the latest tagged release is 0.2.4.

A user shouldn't have to sift through commits to figure out what changed.  Especially when the module in question jumps up 7 minor versions.

Could you please consider maintaining a changelog?

**Comment by burakcan** [comment]
Hi @imcrthy thank you for the suggestion. I really want to maintain a changelog, but it's very hard for me now. 

Actually, this library was not written to be use outside of adphorus (actually, it was my onboarding demo project:) ) and the project structure is not great now to maintain documentation/changelog etc. I'm planning to do a complete refactoring on the project and release 1.0. After that, we'll have tests and be maintaining a changelog/tag system.
