### ISSUE TITLE
Update react dependency

### ISSUE THREAD

**Issue by p4bloch** [Adphorus/react-date-range#90]
Currently I am using React 15.4, and this library expects React 0.14.8. I'm not sure if this is actually a requirement and the upgrade would break everything, but in practice this means that a project using an updated version of React (which is highly recommended) will have to depend upon two versions of `react` in order to use the library. This is definitely a deal breaker which I believe should be fixed as soon as possible.

`npm ls react` output
```
├── react@15.4.1
└─┬ react-date-range@0.9.0
  └── react@0.14.8
```

Also, the react dependency could be moved as a peerDependency to avoid future conflicts.

@burakcan are you aware how difficult it could be to update to latest React version? Thanks!

**Comment by KarandikarMihir** [comment]
@p4bloch Any tips on circumventing this for the time being? It's breaking `react-hot-loader` in our project! :crying_cat_face:

**Comment by p4bloch** [comment]
@KarandikarMihir I did not reach the point of no return on my implementation so I was able to switch to [another library](https://github.com/react-component/calendar).

**Comment by KarandikarMihir** [comment]
@p4bloch Okay.. Thanks a ton!
