### ISSUE TITLE
Allow passing custom classNames to exposed components

### ISSUE THREAD

**Issue by p4bloch** [Adphorus/react-date-range#91]
In #3 the approach taken was to use a fixed className. What I am suggesting here now is to allow extension, so a User can do this `<Calendar className="my-calendar" />`. Right now the `className` prop a parent sends is being discarded. This is useful so each instance can be styled differently, or when you are using a library like cssModules and you want to avoid using the global css namespace.

I think this change can be done fairly easily, changing the `className` attribute on the root element of each exposed component. In `Calendar`, for example, we would change
`className='rdr-MonthAndYear-innerWrapper'` for 
`className={classNames('rdr-MonthAndYear-innerWrapper', props.className)}` using the `classnames` library on which we already depend on.

@burakcan what do you think?

**Comment by mkg0** [comment]
You can set custom classes for each part of components. Use `classNames` prop like below:

```js
<Calendar
  {...otherProps}
  className={'wrapperClassName'}
  classNames={{
    dateRangeWrapper: 'classname1',
    calendarWrapper: 'classname2',
}}
/>
```
You can see full classname list from [here](https://github.com/Adphorus/react-date-range/blob/master/src/styles.js)
